### ISSUE TITLE
NoMethodError (undefined method `gsub' for nil:NilClass)

### ISSUE THREAD

**Issue by ivan-fedorenkov** [janko-m/paperclip-dropbox#13]
Hello!

I have created a small application, using the instructions from the readme file.

Here is the model code:

``` ruby
class User < ActiveRecord::Base
  attr_accessible :avatar
  has_attached_file :avatar, 
    :styles => { :medium => "300x300>", :thumb => "100x100>" },
    :storage => :dropbox,
    :dropbox_credentials => "#{Rails.root}/config/dropbox.yml",
    :dropbox_options => {
      :path => proc { |style| "#{style}/#{id}_#{avatar.original_filename}" }
    }
end
```

Here is the controller code:

``` ruby
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new( params[:user] )
    if @user.save
      redirect_to @user
    else
      render :action => "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

end
```

So when I try to create a new user, server throws an error:

```
[paperclip] Saving attachments.
   (0.8ms)  rollback transaction
Completed 500 Internal Server Error in 2072ms

NoMethodError (undefined method `gsub' for nil:NilClass):
  app/controllers/users_controller.rb:9:in `create'
```

Local storage works just fine. Could you please look at this?

**Comment by krupali1810** [comment]
Hi

I m getting "NoMethodError (undefined method `gsub' for nil:NilClass)" this error.

 I used a rake task. This task gave me an access_token and access_token_secret but no user_id.

How to get user_id? and how to reslove this error?

**Comment by janko-m** [comment]
That's likely due to changes in the Dropbox API. I'm not maintaining paperclip-dropbox anymore mainly due to those reasons.
