### ISSUE TITLE
:app_key credential is nil

### ISSUE THREAD

**Issue by fabricioraphael** [janko-m/paperclip-dropbox#20]
Hello. I followed the post of you and took a searched on google and found nothing relating to this error. will be someone who could help me? thank you
- the error:

```
:app_key credential is nil
```
- the model:

``` ruby
has_attached_file :image,
    :storage => :dropbox,
    :dropbox_credentials => "#{Rails.root}/config/dropbox.yml",
    :styles => { :original => '670x365#',:big => "550x550#",:medium => "400x400#",:small => "50x50#"},
    :dropbox_options => {:path => proc { |style| "#{style}/#{id}_#{image.original_filename}" }}
```
- the config/dropbox.yml

``` erb
development:
    app_key:                <%= ENV["5lhbi547cja849d"] %>
    app_secret:             <%= ENV["khzu0wikjxgo7se"] %>
    access_token:           <%= ENV["kw91h3cxpadr8tt"] %>
    access_token_secret:    <%= ENV["acb2v71pbp5b3b1"] %>
    user_id:                <%= ENV["153413001"] %>
    access_type:            <%= ENV["dropbox"] %>
```

**Comment by WilfredKesh** [comment]
Only the secret keys should be used in the application.yml.

In your

 application.yml 

//use x's in future to prevent exposing secret keys

APP_SECRET: "xxxxxxxxxxxxxxxxxxxxx"
ACCESS_TOKEN_SECRET: "xxxxxxxxxxxxxxxxxxxxx"

then in 

dropbox.yml

  app_key:                 "5lhbi547cja849d"
  app_secret:             <%= ENV["APP_SECRET"] %>
  access_token:         "kw91h3cxpadr8tt""
  access_token_secret:   <%= ENV["ACCESS_TOKEN_SECRET"] %>
  user_id:                 "153413001"
  access_type:            "dropbox"

THEN IN COMMAND PROMPT/TERMINAL

$ figaro heroku:set -e production                                    # if you're using Figaro v1.0
$ rake figaro:heroku                                                       # if you're using Figaro v0.7

Last step: Check if heroku has the keys registered, by running the following on the command line


$ heroku config
