### ISSUE TITLE
rake dropbox:authorize returns 401

### ISSUE THREAD

**Issue by danieldevries** [janko-m/paperclip-dropbox#55]
Credentials are ok, because if I visit the URL in my browser I can authorize my app but from the command line I get a 401.

```
DropboxAuthError: Couldn't get access token.  Server returned 401: Unauthorized.
```

**Comment by janko-m** [comment]
This happens after you confirm in the command-line that you've authorized through the browser?

**Comment by danieldevries** [comment]
Yes, but I tried again after creating a new app and everything works. I think the error was on my end, sorry!
